name: 'virtual-enviroment-version'
description: 'show virtual enviroment version'
author: 'starfish719'
inputs:
  target:
    description: 'input check version target'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
